max_range: 5.0
octomap_frame: world
octomap_resolution: 0.01
sensors:
  - filtered_cloud_topic: filtered_cloud
    max_range: 1.0
    max_update_rate: 1.0
    padding_offset: 0.1
    padding_scale: 1.0
    point_cloud_topic: /camera1/depth/points
    point_subsample: 1
    sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater